name: CI/CD Pipeline
on:
  push:
    branches: ["main"] 
jobs:
  ci:
    runs-on: ubuntu-latest 
    steps:
      #Checar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2
      #Autenticar no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and Push Image Docker
        uses: docker/build-push-action@v6
        with: 
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            jeressy/fake-shop:latest
            jeressy/fake-shop:v${{ github.run_number }}

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Config o kubectl 
        run: aws eks update-kubeconfig --name aula-k8s

      - name: Deploy manifests to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              ./k8s/deployment.yaml
          images: |
              jeressy/fake-shop:v${{ github.run_number }}